name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          bash build.sh

      - name: start mysql / redis
        run: |
          sudo systemctl start mysql.service
          apt update
          apt install redis

      - name: Test
        run: go test -tags="redis,sqlite" -race -v ./...

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: cmd/authlibskin/out/*
          name: ${{ github.run_number }}
